---
title: "README"
output: html_document

#Assignment submission to Elmer Peramo
#Rayel_R_Assignment1.R
#RosarioRayel_MP.R

#Assignment1:
#   A. WHO dataset - used to derive information for the following:
#     1.Find the country with the lowest literacy rate.
#     2.Find the richest country in Europe based on GNI.
#     3.The mean life expectancy of countries in Africa.
#     4.Find the number of countries with population over 10M
#     5.Find names of the country (top 5) in the Americas with the highest child mortality rate.

#   B. The NBA Historical Performance Dataset
#     1.Find the year the Chicago Bulls has its highest winning percentage
#     2.Find the teams with an even win-loss record(i.e. the teams whose recorded win pct for the year are 0.500).

#   C.The season stats dataset
#     1.Find the player with the highest three point attempt rate.
#     2.Find the players with the highest free throw rate in season.
#     3.Find the year The King recorded his highest number of points.
#     4.The year the GOAT scored his most number of points.
#     5.Get Kobe's PER when his MP(minutes played) is the lowest.

#   D.The National Universities Rankings
#     1.Find the university with the most number of undergrad.
#     2.Find the average tuition of the top ten universities.

#Assignment2: Machine Problem
#   1. Making use of all of the functions on removal of NA values.
#   2. Computation of a compound interest of an investment
#   3. Function that accepts an integer and outputs a Boolean value (TRUE or FALSE)
#   4. Computation of net pay
#   5. Function that accepts a Date as argument and outputs the day of the week as characters with the use of modulo


#Lastly, it is kinda Fun pushing the git
#Computing in Analytics is very much appreciated
#Thank you Sir!